import type { RawCourseImportRow } from "@/types/course-import";

export const OFFICIAL_IMPORT_SOURCE_NAME = "Trilha oficial — Especificação v1.0";
export const OFFICIAL_IMPORT_KEY = "official-course-track-v1-56";

export const officialCourseRows: RawCourseImportRow[] = [
  { sourceId: 1, name: "Excel Básico", platform: "Fundação Bradesco", area: "Excel", workloadHours: 29, status: "Concluído", kind: "Curso" },
  { sourceId: 2, name: "Excel Intermediário", platform: "Fundação Bradesco", area: "Excel", workloadHours: 28, status: "Concluído", kind: "Curso" },
  { sourceId: 3, name: "Excel Avançado", platform: "Fundação Bradesco", area: "Excel", workloadHours: 31, status: "Em andamento", kind: "Curso" },
  { sourceId: 4, name: "Microsoft Word", platform: "Fundação Bradesco", area: "Pacote Office", workloadHours: 24, status: "Planejado", kind: "Curso" },
  { sourceId: 5, name: "Organização Pessoal e Gestão do Tempo", platform: "Fundação Bradesco", area: "Produtividade", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 6, name: "Comunicação Empresarial", platform: "Fundação Bradesco", area: "Comunicação", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 7, name: "Oratória e Comunicação", platform: "SEBRAE", area: "Comunicação", workloadHours: 16, status: "Planejado", kind: "Curso" },
  { sourceId: 8, name: "Microsoft Outlook", platform: "Fundação Bradesco", area: "Pacote Office", workloadHours: 14, status: "Planejado", kind: "Curso" },
  { sourceId: 9, name: "Microsoft PowerPoint", platform: "Fundação Bradesco", area: "Pacote Office", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 10, name: "Atendimento ao Cliente", platform: "Fundação Bradesco", area: "Desenvolvimento Profissional", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 11, name: "Inteligência Emocional", platform: "ENAP", area: "Desenvolvimento Profissional", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 12, name: "Gestão de Projetos", platform: "ENAP", area: "Gestão de Projetos", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 13, name: "LGPD", platform: "ENAP", area: "Segurança e LGPD", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 14, name: "Inteligência Artificial para o Trabalho", platform: "Microsoft Learn", area: "Inteligência Artificial", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 15, name: "Produtividade no Microsoft 365", platform: "Microsoft Learn", area: "Produtividade", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 16, name: "Excel com IA", platform: "Microsoft Learn", area: "Excel", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 17, name: "Matemática Financeira", platform: "Fundação Bradesco", area: "Finanças", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 18, name: "Educação Financeira", platform: "ENAP", area: "Finanças", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 19, name: "Contabilidade Básica", platform: "ENAP", area: "Contabilidade", workloadHours: 30, status: "Planejado", kind: "Curso" },
  { sourceId: 20, name: "Administração Financeira", platform: "ENAP", area: "Finanças", workloadHours: 30, status: "Planejado", kind: "Curso" },
  { sourceId: 21, name: "Gestão Financeira", platform: "SEBRAE", area: "Finanças", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 22, name: "Fluxo de Caixa", platform: "SEBRAE", area: "Finanças", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 23, name: "Planejamento Orçamentário", platform: "ENAP", area: "Finanças", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 24, name: "Análise de Custos", platform: "SEBRAE", area: "Controladoria", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 25, name: "Controladoria", platform: "ENAP", area: "Controladoria", workloadHours: 30, status: "Planejado", kind: "Curso" },
  { sourceId: 26, name: "Power Query", platform: "Microsoft Learn", area: "Power BI", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 27, name: "Power BI – Introdução", platform: "ENAP", area: "Power BI", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 28, name: "Power BI – Intermediário", platform: "Microsoft Learn", area: "Power BI", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 29, name: "Power BI para Finanças", platform: "Microsoft Learn", area: "Power BI", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 30, name: "DAX", platform: "Microsoft Learn", area: "Power BI", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 31, name: "Modelagem de Dados", platform: "Microsoft Learn", area: "Análise de Dados", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 32, name: "Dashboards", platform: "Microsoft Learn", area: "Power BI", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 33, name: "KPIs e Indicadores", platform: "Microsoft Learn", area: "Power BI", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 34, name: "Storytelling com Dados", platform: "Microsoft Learn", area: "Análise de Dados", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 35, name: "Business Intelligence", platform: "Microsoft Learn", area: "Power BI", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 36, name: "Power Pivot", platform: "Microsoft Learn", area: "Power BI", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 37, name: "Power BI Service", platform: "Microsoft Learn", area: "Power BI", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 38, name: "SQL Básico", platform: "Fundação Bradesco", area: "Banco de Dados", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 39, name: "SQL Intermediário", platform: "Cisco Networking Academy", area: "Banco de Dados", workloadHours: 40, status: "Planejado", kind: "Curso" },
  { sourceId: 40, name: "Banco de Dados", platform: "Cisco Networking Academy", area: "Banco de Dados", workloadHours: 40, status: "Planejado", kind: "Curso" },
  { sourceId: 41, name: "Estatística para Análise de Dados", platform: "ENAP", area: "Análise de Dados", workloadHours: 30, status: "Planejado", kind: "Curso" },
  { sourceId: 42, name: "Python para Análise de Dados", platform: "Microsoft Learn", area: "Programação", workloadHours: 40, status: "Planejado", kind: "Curso" },
  { sourceId: 43, name: "Git e GitHub", platform: "Microsoft Learn", area: "Programação", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 44, name: "Power Automate", platform: "Microsoft Learn", area: "Automação", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 45, name: "Power Apps", platform: "Microsoft Learn", area: "Automação", workloadHours: 15, status: "Planejado", kind: "Curso" },
  { sourceId: 46, name: "Microsoft Copilot", platform: "Microsoft Learn", area: "Inteligência Artificial", workloadHours: 10, status: "Planejado", kind: "Curso" },
  { sourceId: 47, name: "Negociação Profissional", platform: "SEBRAE", area: "Desenvolvimento Profissional", workloadHours: 20, status: "Planejado", kind: "Curso" },
  { sourceId: 48, name: "Etiqueta e Postura Profissional", platform: "SEBRAE", area: "Desenvolvimento Profissional", workloadHours: 12, status: "Planejado", kind: "Curso" },
  { sourceId: 49, name: "Inglês para Negócios", platform: "Fundação Bradesco", area: "Inglês", workloadHours: 30, status: "Planejado", kind: "Curso" },
  { sourceId: 50, name: "Microsoft Office Specialist – Excel Associate", platform: "Microsoft", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 51, name: "Microsoft PL-300 – Power BI Data Analyst", platform: "Microsoft", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 52, name: "Scrum Foundation Professional Certificate", platform: "Scrum Study", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 53, name: "Lean Six Sigma White Belt", platform: "Outros", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 54, name: "Lean Six Sigma Yellow Belt", platform: "Outros", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 55, name: "Microsoft Azure Fundamentals (AZ-900)", platform: "Microsoft", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
  { sourceId: 56, name: "Microsoft Azure Data Fundamentals (DP-900)", platform: "Microsoft", area: "Certificações", workloadHours: 0, status: "Planejado", kind: "Certificação" },
];
