-- Sistema de Gestão de Estudos – Roberta
-- Versão 0.4: perfis, preferências e listas configuráveis
-- Execute no SQL Editor do Supabase em um projeto já configurado.

create extension if not exists pgcrypto with schema extensions;

create or replace function public.normalize_label(value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select lower(
    regexp_replace(
      translate(
        trim(coalesce(value, '')),
        'áàâãäéèêëíìîïóòôõöúùûüçñÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑ',
        'aaaaaeeeeiiiiooooouuuucnAAAAAEEEEIIIIOOOOOUUUUCN'
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) >= 3),
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.user_settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  monthly_goal_hours numeric(6,2) not null default 40 check (monthly_goal_hours > 0 and monthly_goal_hours <= 744),
  annual_certificate_goal integer not null default 12 check (annual_certificate_goal >= 0 and annual_certificate_goal <= 999),
  tracking_year integer not null default extract(year from current_date)::integer check (tracking_year between 2000 and 2100),
  consistency_days integer not null default 30 check (consistency_days between 7 and 365),
  current_course_id uuid,
  home_page text not null default 'estudos' check (home_page in ('estudos', 'cursos', 'dashboard', 'anotacoes', 'certificados')),
  timezone text not null default 'America/Sao_Paulo',
  locale text not null default 'pt-BR',
  date_format text not null default 'DD/MM/AAAA' check (date_format in ('DD/MM/AAAA', 'AAAA-MM-DD')),
  time_format text not null default '24h' check (time_format in ('24h', '12h')),
  theme text not null default 'system' check (theme in ('light', 'dark', 'system')),
  accent_color text not null default '#1768d3' check (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  interface_density text not null default 'default' check (interface_density in ('compact', 'default', 'comfortable')),
  rounding text not null default 'default' check (rounding in ('small', 'default', 'large')),
  remember_filters boolean not null default true,
  show_tips boolean not null default true,
  save_current_course boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.platforms (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80),
  normalized_name text not null,
  is_system boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.areas (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80),
  normalized_name text not null,
  is_system boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_types (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80),
  normalized_name text not null,
  is_system boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.note_categories (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 2 and 80),
  normalized_name text not null,
  is_system boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists platforms_user_active_name_unique
  on public.platforms(user_id, normalized_name)
  where archived_at is null;
create unique index if not exists areas_user_active_name_unique
  on public.areas(user_id, normalized_name)
  where archived_at is null;
create unique index if not exists study_types_user_active_name_unique
  on public.study_types(user_id, normalized_name)
  where archived_at is null;
create unique index if not exists note_categories_user_active_name_unique
  on public.note_categories(user_id, normalized_name)
  where archived_at is null;

create index if not exists platforms_user_archived_idx on public.platforms(user_id, archived_at);
create index if not exists areas_user_archived_idx on public.areas(user_id, archived_at);
create index if not exists study_types_user_archived_idx on public.study_types(user_id, archived_at);
create index if not exists note_categories_user_archived_idx on public.note_categories(user_id, archived_at);
create index if not exists audit_logs_user_created_idx on public.audit_logs(user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_normalized_name()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.name = trim(new.name);
  new.normalized_name = public.normalize_label(new.name);
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_settings_set_updated_at on public.user_settings;
create trigger user_settings_set_updated_at before update on public.user_settings
for each row execute function public.set_updated_at();

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['platforms', 'areas', 'study_types', 'note_categories']
  LOOP
    EXECUTE format('drop trigger if exists %I_set_updated_at on public.%I', table_name, table_name);
    EXECUTE format('create trigger %I_set_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
    EXECUTE format('drop trigger if exists %I_set_normalized_name on public.%I', table_name, table_name);
    EXECUTE format('create trigger %I_set_normalized_name before insert or update of name on public.%I for each row execute function public.set_normalized_name()', table_name, table_name);
  END LOOP;
END $$;

create or replace function public.seed_user_defaults(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_settings(user_id)
  values (target_user_id)
  on conflict (user_id) do nothing;

  insert into public.platforms(user_id, name, normalized_name, is_system)
  select target_user_id, value, public.normalize_label(value), true
  from unnest(array[
    'Fundação Bradesco', 'ENAP', 'Microsoft Learn', 'SEBRAE',
    'Cisco Networking Academy', 'Khan Academy', 'Escola Virtual.Gov', 'Outros'
  ]) as value
  on conflict do nothing;

  insert into public.areas(user_id, name, normalized_name, is_system)
  select target_user_id, value, public.normalize_label(value), true
  from unnest(array[
    'Excel', 'Pacote Office', 'Comunicação', 'Desenvolvimento Profissional',
    'Produtividade', 'Gestão de Projetos', 'Segurança e LGPD', 'Inteligência Artificial',
    'Finanças', 'Contabilidade', 'Controladoria', 'Power BI', 'Análise de Dados',
    'Banco de Dados', 'Programação', 'Automação', 'Inglês', 'Certificações'
  ]) as value
  on conflict do nothing;

  insert into public.study_types(user_id, name, normalized_name, is_system)
  select target_user_id, value, public.normalize_label(value), true
  from unnest(array['Aula', 'Revisão', 'Exercício', 'Projeto', 'Simulado', 'Leitura']) as value
  on conflict do nothing;

  insert into public.note_categories(user_id, name, normalized_name, is_system)
  select target_user_id, value, public.normalize_label(value), true
  from unnest(array['Resumo', 'Dúvida', 'Fórmula', 'Conceito', 'Exercício', 'Ideia', 'Revisão']) as value
  on conflict do nothing;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, name, avatar_url)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1), 'Usuário'),
    nullif(trim(new.raw_user_meta_data ->> 'avatar_url'), '')
  )
  on conflict (id) do update
    set name = excluded.name,
        avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url);

  perform public.seed_user_defaults(new.id);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Migração dos usuários que já existiam antes da v0.4.
insert into public.profiles(id, name, avatar_url)
select
  id,
  coalesce(nullif(trim(raw_user_meta_data ->> 'name'), ''), split_part(email, '@', 1), 'Usuário'),
  nullif(trim(raw_user_meta_data ->> 'avatar_url'), '')
from auth.users
on conflict (id) do update
  set name = excluded.name,
      avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url);

DO $$
DECLARE
  existing_user record;
BEGIN
  FOR existing_user IN select id from auth.users
  LOOP
    PERFORM public.seed_user_defaults(existing_user.id);
  END LOOP;
END $$;

alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.platforms enable row level security;
alter table public.areas enable row level security;
alter table public.study_types enable row level security;
alter table public.note_categories enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using ((select auth.uid()) = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "settings_select_own" on public.user_settings;
create policy "settings_select_own" on public.user_settings for select using ((select auth.uid()) = user_id);
drop policy if exists "settings_update_own" on public.user_settings;
create policy "settings_update_own" on public.user_settings for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "settings_insert_own" on public.user_settings;
create policy "settings_insert_own" on public.user_settings for insert with check ((select auth.uid()) = user_id);

DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['platforms', 'areas', 'study_types', 'note_categories']
  LOOP
    EXECUTE format('drop policy if exists %I on public.%I', table_name || '_select_own', table_name);
    EXECUTE format('create policy %I on public.%I for select using ((select auth.uid()) = user_id)', table_name || '_select_own', table_name);
    EXECUTE format('drop policy if exists %I on public.%I', table_name || '_insert_own', table_name);
    EXECUTE format('create policy %I on public.%I for insert with check ((select auth.uid()) = user_id)', table_name || '_insert_own', table_name);
    EXECUTE format('drop policy if exists %I on public.%I', table_name || '_update_own', table_name);
    EXECUTE format('create policy %I on public.%I for update using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)', table_name || '_update_own', table_name);
    EXECUTE format('drop policy if exists %I on public.%I', table_name || '_delete_own', table_name);
    EXECUTE format('create policy %I on public.%I for delete using ((select auth.uid()) = user_id)', table_name || '_delete_own', table_name);
  END LOOP;
END $$;

drop policy if exists "audit_logs_select_own" on public.audit_logs;
create policy "audit_logs_select_own" on public.audit_logs for select using ((select auth.uid()) = user_id);
drop policy if exists "audit_logs_insert_own" on public.audit_logs;
create policy "audit_logs_insert_own" on public.audit_logs for insert with check ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert, update on public.user_settings to authenticated;
grant select, insert, update, delete on public.platforms to authenticated;
grant select, insert, update, delete on public.areas to authenticated;
grant select, insert, update, delete on public.study_types to authenticated;
grant select, insert, update, delete on public.note_categories to authenticated;
grant select, insert on public.audit_logs to authenticated;

comment on table public.user_settings is 'Preferências persistentes da conta na versão 0.4.';
comment on table public.platforms is 'Lista de plataformas configurável por usuário.';
comment on table public.areas is 'Lista de áreas de estudo configurável por usuário.';
comment on table public.study_types is 'Lista de tipos de estudo configurável por usuário.';
comment on table public.note_categories is 'Lista de categorias de anotação configurável por usuário.';
